baseURL = "im.ttxxzsk.top"
languageCode = "zh-CN"
title = "阿松导航页"
theme = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower = true
hasCJKLanguage = true
publishDir = "docs"


[params]
    author        = "asong"
    description   = "阿松导航 | 施在必行"
    siteurl       = "./"
    upload        = "https://blog.ttxxzsk.top/"  # 左侧导航栏的"网站提交"
    about         = "./about"   # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/asong2022"  
    enablePreLoad = true		    		           # 网站完全打开前预加载动画
    textPreLoad   = "阿松导航页" 		           # 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false                                          # 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			   # 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"             # logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    baiduhmid     = 'efccc04cb44fc49faddac5876180b369'             # 百度统计 hm.src 的 ID

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "https://i.niupic.com/images/2023/01/08/af19.png"
    searchImageL      = "assets/images/bg-dna.jpg"		#搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		#搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：i-shi@qq.com <br/>&copy; 2023 - {year} By [asong 阿松](https://ttxxzsk.top/) | [浙ICP备2022036691号-1](http://beian.miit.gov.cn/)<br/>'
